// <auto-generated />
using System;
using Catalog.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catalog.API.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20251108143957_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAT")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1c7967fb-25c5-4c71-9b12-09596b946e94"),
                            CreatedAt = new DateTime(2025, 11, 8, 14, 39, 56, 608, DateTimeKind.Utc).AddTicks(9746),
                            Name = "Lenovo",
                            Price = 999.99m,
                            StockQuantity = 10,
                            UpdatedAT = new DateTime(2025, 11, 8, 14, 39, 56, 608, DateTimeKind.Utc).AddTicks(9750)
                        },
                        new
                        {
                            Id = new Guid("2d3f45f1-823e-4773-a454-59f5dea3cc7c"),
                            CreatedAt = new DateTime(2025, 11, 8, 14, 39, 56, 608, DateTimeKind.Utc).AddTicks(9754),
                            Name = "Iphone 15",
                            Price = 800.77m,
                            StockQuantity = 10,
                            UpdatedAT = new DateTime(2025, 11, 8, 14, 39, 56, 608, DateTimeKind.Utc).AddTicks(9754)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
