// <auto-generated />
using System;
using Catalog.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catalog.API.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20251115235934_initialCatalogMigration")]
    partial class initialCatalogMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAT")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0bdab38a-2dd1-4ec5-90ef-3eac44b19444"),
                            CreatedAt = new DateTime(2025, 11, 15, 23, 59, 33, 694, DateTimeKind.Utc).AddTicks(8810),
                            Name = "Lenovo",
                            Price = 999.99m,
                            StockQuantity = 10,
                            UpdatedAT = new DateTime(2025, 11, 15, 23, 59, 33, 694, DateTimeKind.Utc).AddTicks(8812)
                        },
                        new
                        {
                            Id = new Guid("d9261391-ea5a-486d-aa28-abeb52653d74"),
                            CreatedAt = new DateTime(2025, 11, 15, 23, 59, 33, 694, DateTimeKind.Utc).AddTicks(8815),
                            Name = "Iphone 15",
                            Price = 800.77m,
                            StockQuantity = 10,
                            UpdatedAT = new DateTime(2025, 11, 15, 23, 59, 33, 694, DateTimeKind.Utc).AddTicks(8815)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
