apiVersion: v1
kind: Service
metadata:
  name: cart-api
  namespace: centeshop
spec:
  selector:
    app: cart-api
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-api
  namespace: centeshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart-api
  template:
    metadata:
      labels:
        app: cart-api
    spec:
      containers:
        - name: cart-api
          image: centeshopacr.azurecr.io/cart-api:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"

            # Redis connection string (matches your Program.cs name "Redis")
            - name: ConnectionStrings__Redis
              value: "redis:6379"

            # MassTransit config in code uses host "rabbitMq" – here it's "rabbitmq"
            # so either:
            - name: RabbitMq__Host
              value: "rabbitmq"

            # Optional Seq
            - name: Serilog__WriteTo__0__Args__serverUrl
              value: "http://seq"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
