apiVersion: v1
kind: Service
metadata:
  name: catalog-api
  namespace: centeshop
spec:
  selector:
    app: catalog-api
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
  namespace: centeshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
        - name: catalog-api
          image: centeshopacr.azurecr.io/catalog-api:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"

            # Connection string should match Program.cs: "CatalogDbConnection"
            - name: ConnectionStrings__CatalogDbConnection
              value: "Host=catalog-postgres;Port=5432;Database=catalog_db;Username=admin;Password=cente25;"

            # Serilog/Seq optional – only if your config uses these env vars
            - name: Serilog__WriteTo__0__Args__serverUrl
              value: "http://seq"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
