apiVersion: v1
kind: Service
metadata:
  name: ordering-api
  namespace: centeshop
spec:
  selector:
    app: ordering-api
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordering-api
  namespace: centeshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ordering-api
  template:
    metadata:
      labels:
        app: ordering-api
    spec:
      containers:
        - name: ordering-api
          image: centeshopacr.azurecr.io/ordering-api:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"

            # Match Program.cs: "OrderingDbConnection"
            - name: ConnectionStrings__OrderingDbConnection
              value: "Host=ordering-postgres;Port=5432;Database=ordering_db;Username=admin;Password=cente24;"

            # RabbitMQ host for MassTransit
            - name: RabbitMq__Host
              value: "rabbitmq"

            - name: Serilog__WriteTo__0__Args__serverUrl
              value: "http://seq"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
