# See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

# This stage is used when running from VS in fast mode (Default for Debug configuration)
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081


# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["src/Services/cart/Cart.API/Cart.API.csproj", "src/services/cart/Cart.API/"]
COPY ["src/Services/cart/Cart.Applicaiton/Cart.Application.csproj", "src/Services/cart/Cart.Applicaiton/"]
COPY ["src/Services/cart/Cart.Infrastructure/Cart.Infrastructure.csproj", "src/Services/cart/Cart.Infrastructure/"]
COPY ["src/Services/cart/Cart.Domain/Cart.Domain.csproj", "src/Services/cart/Cart.Domain/"]
COPY ["src/Common/Shared.Library.csproj", "src/Common/"]
RUN dotnet restore "./src/services/cart/Cart.API/Cart.API.csproj"
COPY . .
WORKDIR "/src/src/Services/cart/Cart.API"
RUN dotnet build "./Cart.API.csproj" -c $BUILD_CONFIGURATION -o /app/build

# This stage is used to publish the service project to be copied to the final stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Cart.API.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# This stage is used in production or when running from VS in regular mode (Default when not using the Debug configuration)
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Cart.API.dll"]