// <auto-generated />
using System;
using Catalog.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAT")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("35c23cd6-666d-492c-b972-b0b17ea7c36a"),
                            CreatedAt = new DateTime(2025, 11, 19, 0, 53, 15, 821, DateTimeKind.Utc).AddTicks(6604),
                            Name = "Lenovo",
                            Price = 999.99m,
                            StockQuantity = 10,
                            UpdatedAT = new DateTime(2025, 11, 19, 0, 53, 15, 821, DateTimeKind.Utc).AddTicks(6607)
                        },
                        new
                        {
                            Id = new Guid("b938e2d3-4f45-4519-b1b2-7afceac841ff"),
                            CreatedAt = new DateTime(2025, 11, 19, 0, 53, 15, 821, DateTimeKind.Utc).AddTicks(6610),
                            Name = "Iphone 15",
                            Price = 800.77m,
                            StockQuantity = 10,
                            UpdatedAT = new DateTime(2025, 11, 19, 0, 53, 15, 821, DateTimeKind.Utc).AddTicks(6611)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
